language: node_js
node_js:
  - 10

script:
  - npm run build

deploy:
  - on:
      branch: master
    provider: script
    skip_cleanup: true
    script:
      - export DEPLOY_URL="https://$(jq -r .alias now.json)"
      - script/commit-status now/production "Production deployment" "$DEPLOY_URL" \
          -- bash script/deploy --token="$NOW_TOKEN"
  - on:
      all_branches: true
      condition: $TRAVIS_BRANCH != master
    provider: script
    script:
      - export DEPLOY_URL="https://primer-style-${TRAVIS_BRANCH}.now.sh"
      - script/commit-status now/preview "Preview deployment" "$DEPLOY_URL" \
          -- bash script/deploy-preview --token="$NOW_TOKEN"
    skip_cleanup: true

notifications:
  slack: github:4OisIoqZYyMlWcw3hFtZgbmh
