language: node_js
node_js:
  - 10

script:
  - npm run lint
  - npm run build

deploy:
  - on:
      branch: master
    provider: script
    script: script/deploy --token="$NOW_TOKEN"
    skip_cleanup: true
  - on:
      all_branches: true
    provider: script
    script: script/deploy-preview --token="$NOW_TOKEN"
    skip_cleanup: true
