#!/bin/bash
set -e

mkdir -p static/react
npm install
cd react/docs && npm install && gatsby build --prefix-paths
cd ../ && chmod +x ./script/build-storybook && ./script/build-storybook && npm run build
cp -R ./docs/public/. ../static/react 
