#!/bin/bash
set -e

mkdir -p static/react
npm install

cd react/docs
echo "the PWD is : $PWD. should be react/docs"

npm install
gatsby build
cp -R ./public/. ../../static/react 

cd ../
echo "the PWD is : $PWD, should be project root"

chmod +x ./script/build-storybook.sh
#./script/build-storybook.sh
npm run build
