#!/bin/bash
set -e
branch="$TRAVIS_BRANCH"
root="primer-style-$branch.now.sh"
alias="$branch.primer-style.now.sh"
cat rules.json | perl -pi -e "s/primer-style\.now\.sh/${root}/g" > rules-preview.json
cat rules-preview.json
echo now '[args]'
echo now '[args]' alias $root
echo now '[args]' alias $alias -r rules-preview.json
