name: Deploy to preview environment

on:
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    name: Build and deploy
    uses: primer/.github/.github/workflows/deploy_preview.yml@v1.0.0
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      node_version: 14
      install: yarn
      build: yarn build
      output_dir: public
