name: Build and deploy staging

on:
  push:
    branches:
      - staging

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      has-secrets: ${{ steps.check-secrets.outputs.has-secrets }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - name: Install and build
        run: |
          yarn
          yarn build

      - name: Build redirects
        run: |
          node ./script/redirects.js

      - name: Copy redirects to server root
        run: |
          cp web.config public/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./public/

      - name: Check for secrets
        id: check-secrets
        env:
          has_secrets: >-
            ${{
              secrets.AZURE_STAGING_CLIENT_ID != '' &&
              secrets.AZURE_TENANT_ID != '' &&
              secrets.AZURE_SUBSCRIPTION_ID != '' &&
              1 ||
              ''
            }}
        if: env.has_secrets
        run: |
          echo 'has-secrets=1' >> "$GITHUB_OUTPUT"
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    if: needs.build.outputs.has-secrets

    steps:
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_STAGING_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App service
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'primerstyle'
          slot-name: 'staging'
          package: .
